# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
install:
  - pip install cookiecutter
  - pip install invoke==0.14.0
script:
  - invoke test
